export const MOCK_JOBS = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    category: "Development",
    status: "Active",
    applicants: 47,
    datePosted: "2025-05-15",
    location: "Remote",
    type: "Full-time",
  },
  {
    id: "2",
    title: "UI/UX Designer",
    category: "Design",
    status: "Active",
    applicants: 23,
    datePosted: "2025-05-20",
    location: "New York, US",
    type: "Full-time",
  },
  {
    id: "3",
    title: "Marketing Manager",
    category: "Marketing",
    status: "Closed",
    applicants: 89,
    datePosted: "2025-04-10",
    location: "London, UK",
    type: "Full-time",
  },
  {
    id: "4",
    title: "Sales Representative",
    category: "Sales",
    status: "Draft",
    applicants: 0,
    datePosted: "2025-06-01",
    location: "Dhaka, BD",
    type: "Part-time",
  },
  {
    id: "5",
    title: "Backend Engineer",
    category: "Development",
    status: "Active",
    applicants: 31,
    datePosted: "2025-05-25",
    location: "San Francisco, US",
    type: "Full-time",
  },
  {
    id: "6",
    title: "Product Designer",
    category: "Design",
    status: "Draft",
    applicants: 0,
    datePosted: "2025-06-05",
    location: "Remote",
    type: "Contract",
  },
];
